name: Get Latest Commit From Another Repo Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name of target repo"
        required: true
        default: "main"

jobs:
  get-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/dependency-repo
          ref: ${{ github.event.inputs.branch }}

      - name: Print short commit id
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "Latest commit short SHA: $SHORT_SHA"